# Generated by Django 3.2.8 on 2021-10-15 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome da categoria')),
                ('tipo', models.IntegerField(choices=[(1, 'Receita'), (2, 'Despesa')], default=2, verbose_name='Tipo da categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Receita'), (2, 'Despesa')], default=2, verbose_name='Tipo da Movimentação')),
                ('liquidada', models.BooleanField(default=False, editable=False, verbose_name='Despesa descontada/receita recebida?')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da movimentação')),
                ('data', models.DateField(verbose_name='Data da movimentação')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categoria_movimentacao', to='movimentacoes.categoria', verbose_name='Conta em que a movimentação ocorreu')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conta_movimentacao', to='contas.conta', verbose_name='Conta em que a movimentação ocorreu')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'db_table': 'movimentacao',
            },
        ),
    ]
