# Generated by Django 3.2.8 on 2021-10-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da conta')),
                ('tipo', models.IntegerField(choices=[(1, 'Conta Salário'), (2, 'Conta Corrente'), (3, 'Conta Poupança')], default=2, verbose_name='Tipo de conta')),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo da conta')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'db_table': 'conta',
            },
        ),
    ]
